# Generated by Django 4.0.2 on 2022-03-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiber', '0002_alter_sensor_distance_alter_sensor_splice_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='distance',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Distancia'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='splice_loss',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Perda'),
        ),
    ]
