# Generated by Django 4.0.2 on 2022-03-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiber', '0003_alter_sensor_distance_alter_sensor_splice_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='rua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rua'),
        ),
    ]
