# Generated by Django 4.0.2 on 2022-03-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiber', '0004_sensor_rua'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='status',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('COM VAZAMENTO', 'Com Vazamento'), ('EM MANUTENCAO', 'Em Manutenção'), ('REPARO CONCLUIDO', 'Reparo concluído')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
