# Generated by Django 4.0.2 on 2022-03-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiber', '0006_alter_sensor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='logitude'),
        ),
    ]
